### ISSUE TITLE
Use with Fargate and ALB?

### ISSUE THREAD

**Issue by mattplindsay** [aws-samples/aws-containers-task-definitions#5]
Hi, this is great, but I'm having huge issues keeping targets healthy in a load balanced ECS configuration with an Application Load Balancer. 

Does anyone have any config for listeners and healthchecks in this sort of setup?

Many thanks

**Comment by smoell** [comment]
Hi,

sorry for answering so late ...

Here is on example how to implement something like this (it's my pet project): https://github.com/aws-samples/reactive-refarch-cloudformation/blob/master/services/tracking-service/service.yaml
